# Build stage
FROM node:14.17-alpine as build

WORKDIR /app

COPY package.json ./

RUN npm install

COPY . .

RUN npm run build --verbose

# Staging
FROM nginx:1.21-alpine

COPY --from=build /app/build /usr/share/nginx/html

# Copy NGINX configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

#ENV REACT_APP_BACKEND_URL=http://localhost:8111

CMD ["nginx", "-g", "daemon off;"]