# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo:4.4.18
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - /var/backups/mongodb:/data/backup

  backend:
    depends_on:
      - mongo
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    restart: always
    ports:
      - 8111:80
    environment:
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example
      MONGODB_PORT: 27017
      MONGODB_URL: mongo

  frontend:
    depends_on:
      - mongo 
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile_local
    stdin_open: true # docker run -i (But why?)
    tty: true        # docker run -t (But why?)
    image: frontend
    restart: always
    ports:
      - 3000:3000
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8111
    profiles:
      - local

  frontend_production:
    depends_on:
      - mongo 
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile_production
      args:
        REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
    stdin_open: true # docker run -i (But why?)
    tty: true        # docker run -t (But why?)
    image: frontend
    restart: always
    ports:
      - 80:80
    profiles:
      - production