name: DevOps_App_Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: [ self-hosted , mytesthost ]

    steps:
    - uses: actions/checkout@v3
    - name: Build Backend App
      run: docker compose build --no-cache backend
    - name: Get host IP and set as env var
      run: |
        HOST_IP=$(curl -s https://api.ipify.org)
        echo "HOST_IP=$HOST_IP" >> "$GITHUB_ENV"
    - name: Build Frontend App
      run: docker compose build --no-cache frontend_production
      env:
        REACT_APP_BACKEND_URL: "http://${{ env.HOST_IP }}:8111"    

  deploy:
    needs: build
    runs-on: [ self-hosted , mytesthost ]
    steps:
    - name: Deploy and start app
      run: docker compose --profile production up -d        

  test:
    needs: deploy
    runs-on: [ self-hosted , mytesthost ]
    steps:
    - name: Build and Run Tests for Frontend App
      run: |
        docker build -t app_test -f frontend/Dockerfile_local frontend
        docker run -d --name app_test_container app_test
        docker exec app_test_container npm test -- --watchAll=false --passWithNoTests
        docker rm app_test_container -f

    - name: Docker Images CleanUp
      run: docker image prune -a -f
